name: hackathon
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^1.0.0
  cupertino_icons: ^1.0.2
  firebase_auth: ^1.0.0
  firebase_core: ^1.0.0
  firebase_database: ^6.1.0
  flutter_launcher_icons: ^0.9.0
  provider: ^5.0.0
  flutter_search_bar: ^2.1.0
  flutter_barcode_scanner: ^1.0.2
  geolocator: ^5.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
flutter:
  uses-material-design: true
  assets:
    - assets/leaficon.png
    - assets/carniceria-icon.jpg
    - assets/bebidas-icon.jpg
    - assets/frutas-icon.jpg
    - assets/moda-icon.jpg
    - assets/pescado-icon.jpg
    - assets/ropa-icon.jpg
    - assets/business-logo.jpg
    - assets/redbull.png
    

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/leaficon.png"
  adaptive_icon_foreground: "assets/leaficon.png"
